### ISSUE TITLE
Implementing plurals: tracking issue

### ISSUE THREAD

**Issue by davedotluebke** [davedotluebke/old-skool-text-game#84]
List of changes required to fully implement plurals:

- [x]  Changes to `Thing` class:
   - [x] Add `plurality` field which represents the number of this object present (default to 1)
   - [x] Remove current `plural` field which is barely used and now redundant
   - [x] Add `get_volume()` and `get_weight()` methods which multiply the intrinsic volume/weight by the number of objects in the plurality, and return that. Also change everywhere `Thing.weight` and `Thing.volume` are currently referenced to use the getter functions. 
   - [x] Create `Thing.compare()` function to decide whether two Thing objects are identical (and thus suitable for combining into a plurality)
   - [x] Create `Thing.replicate()` function to create a copy of a Thing object when extracting some object(s) from a plurality. 
- [ ]  The Parser will need significant changes to: 
  - [x] check whether Actions affect a plurality, potentially removing a changed object from the plurality as discussed above. In the `parse()` function:
    - [x]  if the 'verb object' providing the action verb is plural (`obj.plurality > 1`), split the object into two objects:
      - call `Thing.replicate()` to create a copy of the object (also adds to `Thing.ID_dict[]`)
      - adjust the plurality fields of the copy and the original object (usually original will have plurality == 1 and copy will have plurality == n-1, where n is the initial plurality)
    - [x] If the direct object is plural (`oDO.plurality > 1`), and the user specified a subset of that plurality (e.g., "light a torch" or "light two torches" when user is carrying a plurality of six torches), split oDO as above.
    - [x] Similarly split the indirect object if plural (`oIDO.plurality > 1`) and necessitated by the user's command.
    - [x] ENACT THE VERB on the original 
    - [x] compare the copy and original objects (if any) for `obj`, `oDO`, and `oIDO`
      - the comparison should ignore the `plurality` and `id` fields
      - if they are the same, the action didn't affect the object - merge it back into a single plurality by setting the plurality of the original object back to the initial value and calling `Thing.destroy()` on the copy.
      - [x] *Important*: if the action did affect the object, we will be keeping the copy. If the original object has a heartbeat function registered, we need to register a new heartbeat function for the copy. 
  - [ ] handle pluralities verbally (e.g., "drop 6 gold coins", "put two books in the backpack").
  - [ ] handle adjectives like "first", "second", "third" consistently in the presence of pluralities when given commands like `drop the third wooden torch`. For example when the items in a player's inventory are listed as "three wooden torches" and "a lit wooden torch", if the player types "drop fourth torch" they should drop the lit one. 
    - [ ] support 'any' and 'all' adjectives (e.g., "light any torch" so you don't get the "Which torch did you mean to light?" error message)
- [ ]  Changes to the `Container` class:
   - [x] Containers should support adding to and removing from a plurality when identical objects are inserted or extracted from the Container.
   - [x] Also evaluating weight and volume limits when adding or subtracting things to a Container (including a player's inventory).
   - [ ] Also Containers may want to store a precomputed hash of each object in the `contents` list (per the optimization discussed above)
   - [x] Decide whether to disallow pluralities of Containers, that is, prevent setting the `plurality` field to a value greater than 1. This will avoid dealing with the `contents` field when manipulating plural objects. 
- [ ]  All code that inspects the `contents[]` field will need to deal with plural objects. Let's add examples here as we think of them or find them in the code:
   - [x] Determining whether a room is lit or dark by recursively looking for light sources in the room.
   - [x] Printing out inventory (e.g. "a bunch of wooden torches").
   - [x] `Thing.ID_dict` stores an ID and reference for every object in the game.  *Principle: exactly one unique id exists for the multiple objects represented by an object with `plurality > 1`.* The code that creates and destroys objects as they are merged into and split off of plural objects must correctly maintain the IDs in `Thing.ID_dict`. 
   - [x] When a creature is attacked, it automatically calls the `weapon_and_armor_grab()` function if they aren't wielding any weapons or wearing any armor. This code needs to check if the `plurality` field is set on any objects, so they player can only wield one sword at a time.

**Comment by 1Bayshore** [comment]
We currently have a problem: when we replicate an object to perform an action on it, the `insert` function decides it is identical to the one it was split from and remerges it.
